### ISSUE TITLE
preserve docs for tagged releases

### ISSUE THREAD

**Issue by gonewest818** [plexus/autodoc#4]
For libraries with multiple released versions, it would ideally be the case that developers can access the documentation corresponding to any release. 

So rather than overwrite the latest set of documentation, I'd like to propose `autodoc` should instead maintain a distinct subdirectory for each branch name or tagged release. The directory tree for the `gh-pages` orphan branch could be something like this:
```
gh-pages/
gh-pages/index.html            # the top level index presents links to the subtrees
gh-pages/versions.json         # data file containing the list of subtrees (master, v1.0.0, v1.1.0, ... etc)

gh-pages/master/               # docs for branch "master"
gh-pages/master/index.html
gh-pages/master/css/
gh-pages/master/js/
...

gh-pages/v1.0.0/               # docs for release v1.0.0
gh-pages/v1.0.0/index.html
gh-pages/v1.0.0/css/
gh-pages/v1.0.0/js/
...

gh-pages/v1.1.0/               # docs for release v1.1.0
gh-pages/v1.1.0/index.html
gh-pages/v1.1.0/css/
gh-pages/v1.1.0/js/
...
```

Generating the docs for any release shouldn't delete or change the others. A top level index can be generated, or if you want to separate concerns, then perhaps it's sufficient to publish a json file containing the subtree names and let the caller deal with generating the index.

[edit: fixed cut-n-paste errors in the directory tree example]

**Comment by plexus** [comment]
Hi Neil,

That's a good idea, but it's not easy to implement. Currently the script completely ignores what's already on the gh-pages branch.

I would happily consider a patch that provides this as optional behavior, e.g. when `AUTODOC_VERSIONED=true`.

**Comment by gonewest818** [comment]
I’m going to try. I think it can be done with plumbing commands similar to what you’re doing. 

I’d need to ls-tree whatever is committed on the gh-pages branch, and rearrange it by substituting the new tree at subdirectory “master” in place of the old one. Leaving all other entries in the tree alone. And then commit and push as you are doing now.

**Comment by gonewest818** [comment]
You're encouraged to look at what I'm doing here: https://github.com/gonewest818/autodoc/tree/subdir

The implementation isn't really all that complicated, but those git plumbing commands are all new to me so I'd like to do more testing before sending the pull request.
